waysa-main/config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  devise_for :users
  get '/mypage', to: 'mypage#show', as: 'show'
  get '/mypage_edit', to: 'mypage#edit', as: 'edit'

  post '/mypage', to: 'mypage#update', as: 'update'
  get '/channel_details', to: 'channel_details#show', as: 'channel_details_show'
  get '/video_list', to: 'video_list#show', as: 'video_list_show'
  get '/video_details', to: 'video_details#show', as: 'video_details_show'
  
end

waysa-main/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

waysa-main/app/models/channel.rb
class Channel < ApplicationRecord
    has_many :ChannelInfo, dependent: :destroy, primary_key: 'channel_id'
    has_many :Video, dependent: :destroy
end

waysa-main/app/models/channel_info.rb
class ChannelInfo < ApplicationRecord
    belongs_to :channels, foreign_key: 'channel_id'
end

waysa-main/app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
end

waysa-main/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable

  #has_secure_password
  attr_accessor :user_name
  has_one :profile
  has_many :posts
end

waysa-main/app/models/video.rb
class Video < ApplicationRecord
    belongs_to :channels, foreign_key: 'channel_id'
    has_many :VideoInfo, dependent: :destroy, primary_key: 'video_id'
end

waysa-main/app/models/video_info.rb
class VideoInfo < ApplicationRecord
    belongs_to :Video, foreign_key: 'video_id'
end

waysa-main/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

waysa-main/app/controllers/channel_details_controller.rb
class ChannelDetailsController < ApplicationController
    before_action :authenticate_user!
    
    def show
        @channelInfos = ChannelInfo
            .select(
                'MAX(created_at) AS created_at, 
                channel_infos.channel_name, 
                MAX(channel_infos.channel_subscribers) AS channel_subscribers, 
                MAX(channel_infos.channnel_video_count) AS channnel_video_count, 
                MAX(channel_infos.channel_video_view_count) AS channel_video_view_count')
            .where(channel_id: params[:channel_id])
            .group('DAY(created_at)')
            .order(serial: "DESC")

        @channelInfo = @channelInfos[0]
        redirect_to show_path if @channelInfo.nil?
    end
end

waysa-main/app/controllers/mypage_controller.rb
class MypageController < ApplicationController

    before_action :authenticate_user!

    def show
        # プロフィール取得
        @profile = Profile.find_by(user_id: current_user.id)
        # プロフィールが設定されていない場合、設定画面へ
        if @profile.nil? then
            render "mypage/edit"
        end

        # 登録チャンネル取得
        @channels = Channel.left_joins(:ChannelInfo)
        .select("
            channels.channel_id, 
            channel_infos.channel_name, 
            MAX(channel_infos.serial), 
            MAX(channel_infos.channel_subscribers) AS channel_subscribers, 
            MAX(channel_infos.channnel_video_count) AS channnel_video_count, 
            MAX(channel_infos.channel_video_view_count) AS channel_video_view_count")
            .group(:channel_id)

        #logger.debug profile.inspect
       
        render "mypage/mypage"
    end

    def edit
        @profile = Profile.find_by(user_id: current_user.id)
    end

    def update
        profile = Profile.find_by(user_id: current_user.id)

        #logger.debug params.inspect
        #logger.debug profile.inspect
        if profile.nil? then
            Profile.create(user_id: current_user.id, name: params[:name], comment: params[:comment])
        else
            profile.update(name: params[:name], comment: params[:comment])
            profile.save
        end
        redirect_to '/mypage'
    end
end

waysa-main/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    if user_signed_in? then
      #redirect_to :controller =>
    end
  end
end

waysa-main/app/controllers/video_details_controller.rb
class VideoDetailsController < ApplicationController
    before_action :authenticate_user!

    def show
        @videoInfos = VideoInfo
            .select(
                'MAX(created_at) AS created_at, 
                video_infos.video_title, 
                MAX(video_infos.video_view) AS video_view')
            .where(video_id: params[:video_id])
            .group('DAY(created_at)')
            .order(serial: "DESC")
        
        @channelInfo = ChannelInfo
            .select("channel_infos.channel_name")
            .find_by(channel_id: params[:channel_id])

        redirect_to show_path if @channelInfo.nil?

        @videoInfo = @videoInfos[0]

        redirect_to video_list_show_path(channel_id: params[:channel_id]) if @videoInfo.nil?
    end
end

waysa-main/app/controllers/video_list_controller.rb
class VideoListController < ApplicationController
    before_action :authenticate_user!

    def show
        @videos = Video.left_joins(:VideoInfo)
        .select("
            videos.video_id, 
            videos.video_title, 
            MAX(video_infos.serial), 
            MAX(video_infos.video_view) AS video_view, 
            MAX(videos.video_upload_at) AS video_upload_at, 
            MAX(video_infos.created_at) AS created_at"
        )
        .where(channel_id: params[:channel_id])
        .group(:video_id)
        .order(video_upload_at: "DESC")

        @channelInfo = ChannelInfo
        .select("channel_infos.channel_name")
        .find_by(channel_id: params[:channel_id])
        #logger.debug @channelInfos.inspect

        redirect_to show_path if @channelInfo.nil?
    end
end

waysa-main/app/helpers/application_helper.rb
module ApplicationHelper
end

waysa-main/app/helpers/channel_details_helper.rb
module ChannelDetailsHelper
end

waysa-main/app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

waysa-main/app/helpers/pages_helper.rb
module PagesHelper
end

waysa-main/app/helpers/video_derail_helper.rb
module VideoDerailHelper
end

waysa-main/app/helpers/video_list_helper.rb
module VideoListHelper
end

waysa-main/app/views/channel_details/show.html.erb
<div class="jumbotron" style="width:100%;">
  <h1 class="display-7">チャンネル名: <%= @channelInfo.channel_name %></h1>
  <hr>
  <%= link_to("投稿動画一覧", video_list_show_path(channel_id: params[:channel_id]), class: "btn btn-primary") %>
  <a class="btn btn-primary" href=<%= "https://www.youtube.com/channel/" + params[:channel_id] %> role="button" target="_blank" rel="noopener noreferrer">
    チャンネルページ <i class="bi bi-arrow-up-right-square"></i>
  </a>
</div>

<table class="table table-striped">
  <caption>List of channel info</caption>
  <thead class="thead-dark">
    <tr><th>登録者数</th><th>動画本数</th><th>総再生回数</th><th>更新日時</th></tr>
  </thead>
  <% @channelInfos.each do |channelInfo| %>
	<tr class="bg-light">
        <td><%= channelInfo.channel_subscribers %></td>
        <td><%= channelInfo.channnel_video_count %></td>
        <td><%= channelInfo.channel_video_view_count %></td>
        <td><%= channelInfo.created_at %></td>
    </tr>  
  <% end %>
</table>

waysa-main/app/views/layouts/_header.html.erb
<nav class="sticky-top navbar navbar-expand-sm navbar-dark bg-dark">
	<a href="#" class="navbar-brand"></a>
	<button class="navbar-toggler" type="button" data-toggle="collapse"
		data-target="#navmenu1" aria-controls="navmenu1"
		aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navmenu1">
		<ul class="navbar-nav  mr-auto">
			<li class="nav-item">
				<%= link_to('Top', root_path, {class: "nav-item nav-link ml-auto"}) %>
			</li>
		</ul>
		<ul class="navbar-nav">
			<% if user_signed_in? %>
			<li class="nav-item">
			<% user_profile = Profile.find_by(user_id: current_user.id) %>
				<%= link_to(user_profile.nil? ? "未設定" : user_profile.name, show_path, {class: "nav-item nav-link ml-auto"}) %>
			</li>
			<li class="nav-item">
				<%= link_to("ログアウト", destroy_user_session_path, {class: "nav-item nav-link ml-auto"}) %>
			</li>
			<% else %>
			<li class="nav-item">
				<%= link_to('登録', new_user_registration_path, {class: "nav-item nav-link ml-auto"}) %>
			</li>
			<li class="nav-item">
				<%= link_to('ログイン', new_user_session_path, {class: "nav-item nav-link ml-auto"}) %>
			</li>
			<% end %>
		</ul>
	</div>
</nav>

waysa-main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="background img-fluid pt-4" style="height: auto;">
    <div class="container">
      <% if !notice.blank? %>
        <div class="alert alert-info" role="alert"><%= notice %></div>
      <% end %>
      <% if !alert.blank? %>
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

waysa-main/app/views/mypage/edit.html.erb
<div class="border rounded bg-light p-2">
    <%= form_with url: update_path do |f| %>
        <div class="form-group">
            <%= f.label 'ユーザー名' %>
            <%= f.text_field  :name, class: "form-control", autocomplete: 'off', value: @profile.name %>
        </div> 
        <div class="form-group">
            <%= f.label '自己紹介' %>
            <%= f.text_field  :comment, class: "form-control", autocomplete: 'off' %>
        </div>
        <div class="form-group">
            <%= f.submit "ユーザープロフィール更新", class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

waysa-main/app/views/mypage/mypage.html.erb
<div class="jumbotron" style="width:30rem;">
  <h1 class="display-7">user: <%= @profile.name %></h1>
  <hr class="my-2">
  <p class="lead"><%= @profile.comment %></p>
  <%= form_with url: edit_path, class: 'form-group', method: :get, local: true do |f| %>
      <%= f.submit "編集", class: "btn btn-primary" %>
  <% end %>
</div>

<table class="table table-striped">
  <caption>List of channels</caption>
  <thead class="thead-dark">
    <tr><th>チャンネルID</th><th>チャンネル名</th><th>登録者数</th><th>動画本数</th><th>総再生回数</th></tr>
  </thead>
  <% @channels.each do |channel| %>
	<tr class="bg-light">
        <td><%= link_to(channel.channel_id, channel_details_show_path(channel_id: channel.channel_id)) %></td>
        <td><%= channel.channel_name %></td>
        <td><%= channel.channel_subscribers %></td>
        <td><%= channel.channnel_video_count %></td>
        <td><%= channel.channel_video_view_count %></td>
    </tr>  
  <% end %>
</table>

waysa-main/app/views/top/index.html.erb
<div class="jumbotron jumbotron-fluid rounded bg-light p-2">
    <div class="container">
      <h1 class="display-4">v0.1</h1>
      <p class="lead">rev:1 first release</p>
      <hr class="my-2">
      <h3>基礎機能実装</h3>
      <ul class="list-group mb-3">
        <li class="list-group-item">・ユーザー関連</li>
        <li class="list-group-item">・チャンネル一覧</li>
        <li class="list-group-item">・チャンネル詳細</li>
        <li class="list-group-item">・投稿動画一覧</li>
        <li class="list-group-item">・投稿動画詳細</li>
      </ul>
      <a class="btn btn-primary btn-lg" href="/users/sign_in" role="button">login</a>
    </div>
</div>

<div class="m-4 p-4"></div>

waysa-main/app/views/video_details/show.html.erb
<div class="jumbotron" style="width:100%;">
  <h1 class="display-7">動画名: <%= @videoInfo.video_title %></h1>
  <hr>
  <%= link_to("投稿動画一覧", video_list_show_path(channel_id: params[:channel_id]), class: "btn btn-primary") %>
  <a class="btn btn-primary" href=<%= "https://www.youtube.com/watch?v=" + params[:video_id] %> role="button" target="_blank" rel="noopener noreferrer">
    動画リンク <i class="bi bi-arrow-up-right-square"></i>
  </a>
</div>

<table class="table table-striped">
  <caption>List of video info</caption>
  <thead class="thead-dark">
    <tr><th>動画名</th><th>再生回数</th><th>更新日時</th></tr>
  </thead>
  <% @videoInfos.each do |videoInfo| %>
	<tr class="bg-light">
        <td><%= videoInfo.video_title %></td>
        <td><%= videoInfo.video_view %></td>
        <td><%= videoInfo.created_at %></td>
    </tr>  
  <% end %>
</table>

waysa-main/app/views/video_list/show.html.erb
<div class="jumbotron" style="width:100%;">
  <h1 class="display-7">チャンネル名: <%= @channelInfo.channel_name %></h1>
  <hr>
  <%= link_to("チャンネル詳細", channel_details_show_path(channel_id: params[:channel_id]), class: "btn btn-primary") %>
  <a class="btn btn-primary" href=<%= "https://www.youtube.com/channel/" + params[:channel_id] %> role="button" target="_blank" rel="noopener noreferrer">
    チャンネルページ <i class="bi bi-arrow-up-right-square"></i>
  </a>
</div>

<table class="table table-striped">
  <caption>List of videos by channel</caption>
  <thead class="thead-dark">
    <tr><th>動画ID</th><th>動画名</th><th style="width: 120px;">再生回数</th><th>投稿日</th><th>登録日</th></tr>
  </thead>
    <% @videos.each do |video| %>
	    <tr class="bg-light">
        <td><%= link_to(video.video_id, video_details_show_path(channel_id: params[:channel_id], video_id: video.video_id)) %></td>
        <td><%= video.video_title %></td>
        <td><%= video.video_view %></td>
        <td><%= video.video_upload_at %></td>
        <td><%= video.created_at %></td>
      </tr>  
    <% end %>
</table>